### ISSUE TITLE
Getting Unable to unserialize value error 

### ISSUE THREAD

**Issue by Pykara-majema-magento** [rianorie/magento2-sortcatalogwidget#3]
Hello,

We have installed this module on Magento 2.2.6 and it's working fine. But the problem is it's conflicting other module functionality. 

I'm getting Unable to unserialize value error. Please see the below screenshot:

![unserialize](https://user-images.githubusercontent.com/46442870/57925639-8a42c480-78c6-11e9-9b35-e1c700597183.JPG)

Please have a look at the screenshot.

**Comment by rianorie** [comment]
I think this was fixed
